# projectcapstone:
#   outputs:
#     dev:
#       dataset: order
#       job_execution_timeout_seconds: 300
#       job_retries: 1
#       keyfile: /workspaces/dw-and-bi/Capstone-project/key/dataengineer-415510-cf382b7b19e7.json
#       location: US
#       method: service-account
#       priority: interactive
#       project: dataengineer-415510
#       threads: 1
#       type: bigquery
#   target: dev

projectcapstone:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dataengineer-415510
      dataset: order
      threads: 1 # Must be a value of 1 or greater
      keyfile: /workspaces/dw-and-bi/Capstone-project/key/dataengineer-415510-0058c045978d.json
      OPTIONAL_CONFIG: VALUE
      location: US